'use client';
import { Suspense, useEffect, useMemo, useRef } from 'react';
import { Canvas, useFrame, useThree } from '@react-three/fiber';
import { Environment, Lightformer, Sparkles } from '@react-three/drei';
import * as THREE from 'three';
import GoldenBottle from './GoldenBottle';

export type Pose = { x:number; y:number; ry:number; rz:number; camera:number; cap:number; berry:number; notes:number };
function Bottle({pose,reduced}:{pose:React.RefObject<Pose>;reduced:boolean}) {
 const colors=useMemo(()=>({base:new THREE.Color('#100e0c'),berry:new THREE.Color('#39131f'),background:new THREE.Color()}),[]);
 const group=useRef<THREE.Group>(null);const cap=useRef<THREE.Group>(null);const notes=useRef<THREE.Group>(null);const light=useRef<THREE.PointLight>(null);const atmosphere=useRef<THREE.Group>(null);
 const tilt=useRef({x:0,y:0});
 useFrame(({camera,clock,scene,pointer,size},delta)=>{const p=pose.current; if(!group.current||!cap.current)return;const mobile=size.width/size.height<1.1;const x=mobile?p.x*.22:p.x;const ease=1-Math.exp(-Math.min(delta,.1)*3);tilt.current.x=THREE.MathUtils.lerp(tilt.current.x,reduced||mobile?0:pointer.x*.1,ease);tilt.current.y=THREE.MathUtils.lerp(tilt.current.y,reduced||mobile?0:pointer.y*.04,ease);group.current.position.set(x,p.y+(reduced?0:Math.sin(clock.elapsedTime*.65)*.035),0);group.current.rotation.set(.045+tilt.current.y,p.ry+tilt.current.x,p.rz);cap.current.position.y=1.36+p.cap;camera.position.set(x*.16,.25,p.camera);camera.lookAt(x*.16,.15,0);if(atmosphere.current){atmosphere.current.position.x=x;atmosphere.current.rotation.z=reduced?0:Math.sin(clock.elapsedTime*.15)*.03;}if(light.current){light.current.color.set('#e5ba70');light.current.intensity=7+p.berry*10;}if(notes.current){notes.current.scale.setScalar(Math.max(.001,p.notes));notes.current.rotation.y=reduced?0:clock.elapsedTime*.06;}scene.background=colors.background.copy(colors.base).lerp(colors.berry,p.berry);});
 return <><group ref={group}>
 <GoldenBottle capRef={cap}/>
 </group><group ref={notes} position={[-1.4,0,-.2]}>{[-1,1].map((n,i)=><mesh key={n} position={[n*.28,.2+i*.3,0]}><sphereGeometry args={[.23,24,24]}/><meshPhysicalMaterial color="#660f2b" roughness={.2} clearcoat={1}/></mesh>)}<mesh position={[0,.67,0]} rotation={[0,0,-.4]}><cylinderGeometry args={[.012,.019,.6,8]}/><meshStandardMaterial color="#8d7960"/></mesh>{[0,1,2,3,4].map(i=><mesh key={i} position={[.3+Math.sin(i*1.25)*.22,-.65+Math.cos(i*1.25)*.2,.1]} rotation={[.3,0,i*1.25]} scale={[.12,.35,.055]}><sphereGeometry args={[1,16,16]}/><meshStandardMaterial color="#a5a0c2" roughness={.55}/></mesh>)}<mesh position={[-.2,-1.15,0]} rotation={[.2,.3,.6]}><cylinderGeometry args={[.08,.12,.7,8]}/><meshStandardMaterial color="#795749" roughness={.95}/></mesh></group>
 <group ref={atmosphere} position={[1.8,0,-1.2]}><mesh position={[0,.2,-.3]} scale={[5.5,6,1]}><planeGeometry args={[1,1]}/><shaderMaterial transparent depthWrite={false} vertexShader={'varying vec2 vUv; void main(){vUv=uv; gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}'} fragmentShader={'varying vec2 vUv; void main(){float d=length((vUv-.5)*2.); float a=pow(max(0.,1.-d),2.)*.5; gl_FragColor=vec4(.48,.29,.10,a);}'}/></mesh><mesh position={[0,.22,0]} scale={[1,1.23,1]}><torusGeometry args={[1.65,.003,6,120]}/><meshBasicMaterial color="#ba9762" transparent opacity={.2}/></mesh><mesh position={[0,-1.32,.4]} scale={[3,.25,1]}><planeGeometry args={[1,1]}/><shaderMaterial transparent depthWrite={false} vertexShader={'varying vec2 vUv; void main(){vUv=uv; gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}'} fragmentShader={'varying vec2 vUv; void main(){float d=length((vUv-.5)*2.); gl_FragColor=vec4(0.,0.,0.,pow(max(0.,1.-d),2.)*.6);}'}/></mesh></group>
 <ambientLight intensity={.85}/><spotLight position={[3,5,5]} intensity={55} angle={.6} penumbra={1} color="#f7eade"/><pointLight ref={light} position={[-3,1,2]} intensity={8}/><Environment resolution={128}><Lightformer intensity={5} position={[-4,1,3]} scale={[1.5,8,1]}/><Lightformer intensity={3} position={[4,2,1]} scale={[2,7,1]}/><Lightformer intensity={2} position={[0,2,5]} scale={[3,2,1]}/><Lightformer intensity={2} position={[0,5,-2]} rotation={[Math.PI/2,0,0]} scale={[5,4,1]}/></Environment>{!reduced&&<Sparkles count={24} size={1.2} scale={[10,7,5]} speed={.12} opacity={.16} color="#e7d7d9"/>}</>;
}
export default function BottleScene({pose,reduced,onReady,onFailure}:{pose:React.RefObject<Pose>;reduced:boolean;onReady:()=>void;onFailure:()=>void}) {return <Canvas dpr={[1,1.5]} camera={{position:[0,.25,6.8],fov:35}} gl={{antialias:true,alpha:false,powerPreference:'high-performance'}} onCreated={onReady}><ContextEvents onFailure={onFailure}/><Suspense fallback={null}><Bottle pose={pose} reduced={reduced}/></Suspense></Canvas>;}

function ContextEvents({onFailure}:{onFailure:()=>void}){const gl=useThree(s=>s.gl);useEffect(()=>{const canvas=gl.domElement;canvas.addEventListener('webglcontextlost',onFailure);return()=>canvas.removeEventListener('webglcontextlost',onFailure);},[gl,onFailure]);return null;}
