'use client';
import { Suspense, useEffect, useMemo, useRef } from 'react';
import { Canvas, useFrame, useThree } from '@react-three/fiber';
import { Environment, Lightformer, RoundedBox, Sparkles } from '@react-three/drei';
import * as THREE from 'three';

export type Pose = { x:number; y:number; ry:number; rz:number; camera:number; cap:number; berry:number; notes:number };
function Label() {
 const texture = useMemo(() => { const c=document.createElement('canvas'); c.width=1024;c.height=640;const g=c.getContext('2d')!;g.fillStyle='#e8e4da';g.fillRect(0,0,1024,640);g.strokeStyle='#8d8275';g.lineWidth=2;g.strokeRect(24,24,976,592);g.fillStyle='#252124';g.textAlign='center';g.font='32px Arial';g.fillText('E A U   D E   P A R F U M',512,130);g.font='112px Georgia';g.fillText('SHANNA',512,300);g.font='33px Arial';g.fillText('N I G H T   B L O O M',512,415);g.font='25px Arial';g.fillText('50 ml   /   1.7 fl. oz.',512,546);const t=new THREE.CanvasTexture(c);t.colorSpace=THREE.SRGBColorSpace;return t; },[]);
 useEffect(()=>()=>texture.dispose(),[texture]);
 return <mesh position={[0,-.13,.516]}><planeGeometry args={[1.12,.70]}/><meshBasicMaterial map={texture} toneMapped={false}/></mesh>;
}
function Bottle({pose,reduced}:{pose:React.RefObject<Pose>;reduced:boolean}) {
 const colors=useMemo(()=>({base:new THREE.Color('#101115'),berry:new THREE.Color('#39131f'),background:new THREE.Color()}),[]);
 const group=useRef<THREE.Group>(null);const cap=useRef<THREE.Group>(null);const notes=useRef<THREE.Group>(null);const light=useRef<THREE.PointLight>(null);const atmosphere=useRef<THREE.Group>(null);
 const tilt=useRef({x:0,y:0});
 useFrame(({camera,clock,scene,pointer,size},delta)=>{const p=pose.current; if(!group.current||!cap.current)return;const mobile=size.width/size.height<1.1;const x=mobile?p.x*.22:p.x;const ease=1-Math.exp(-Math.min(delta,.1)*3);tilt.current.x=THREE.MathUtils.lerp(tilt.current.x,reduced||mobile?0:pointer.x*.1,ease);tilt.current.y=THREE.MathUtils.lerp(tilt.current.y,reduced||mobile?0:pointer.y*.04,ease);group.current.position.set(x,p.y+(reduced?0:Math.sin(clock.elapsedTime*.65)*.035),0);group.current.rotation.set(.045+tilt.current.y,p.ry+tilt.current.x,p.rz);cap.current.position.y=1.36+p.cap;camera.position.set(x*.16,.25,p.camera);camera.lookAt(x*.16,.15,0);if(atmosphere.current){atmosphere.current.position.x=x;atmosphere.current.rotation.z=reduced?0:Math.sin(clock.elapsedTime*.15)*.03;}if(light.current){light.current.color.set('#d44b72');light.current.intensity=7+p.berry*10;}if(notes.current){notes.current.scale.setScalar(Math.max(.001,p.notes));notes.current.rotation.y=reduced?0:clock.elapsedTime*.06;}scene.background=colors.background.copy(colors.base).lerp(colors.berry,p.berry);});
 return <><group ref={group}>
 <RoundedBox args={[1.68,2.05,1.02]} radius={.19} smoothness={5}><meshPhysicalMaterial color="#d7c4cd" metalness={.05} roughness={.09} transmission={.8} thickness={.24} ior={1.5} envMapIntensity={1.7} transparent opacity={.65}/></RoundedBox>
 <RoundedBox args={[1.45,1.51,.81]} radius={.13} smoothness={4} position={[0,-.16,0]}><meshPhysicalMaterial color="#822d49" metalness={.02} roughness={.16} transmission={.18} thickness={.45} ior={1.36} clearcoat={.6}/></RoundedBox>
 <RoundedBox args={[1.52,.12,.87]} radius={.05} smoothness={3} position={[0,-.94,0]}><meshPhysicalMaterial color="#ebe2db" transmission={.85} roughness={.08} thickness={.5}/></RoundedBox>
 <mesh position={[0,.94,0]}><cylinderGeometry args={[.24,.31,.24,40]}/><meshPhysicalMaterial color="#ddd3ca" transmission={.9} roughness={.1}/></mesh>
 <mesh position={[0,1.13,0]}><cylinderGeometry args={[.17,.20,.24,32]}/><meshStandardMaterial color="#c4c1bd" metalness={1} roughness={.22}/></mesh>
 <mesh position={[0,1.23,.158]}><circleGeometry args={[.027,16]}/><meshBasicMaterial color="#171719"/></mesh>
 <mesh position={[0,.16,0]}><cylinderGeometry args={[.018,.018,1.68,12]}/><meshPhysicalMaterial color="#eee0d4" transparent opacity={.45}/></mesh>
 <group ref={cap} position={[0,1.36,0]}><RoundedBox args={[.94,.65,.86]} radius={.075} smoothness={3}><meshStandardMaterial color="#bfc0c4" metalness={1} roughness={.23}/></RoundedBox><mesh position={[0,-.29,0]}><boxGeometry args={[.92,.035,.84]}/><meshStandardMaterial color="#444248" metalness={1} roughness={.3}/></mesh><mesh position={[0,.329,0]} rotation={[-Math.PI/2,0,0]}><planeGeometry args={[.48,.36]}/><meshStandardMaterial color="#c8c4be" metalness={.85} roughness={.3}/></mesh></group>
 <Label/>
 </group><group ref={notes} position={[-1.4,0,-.2]}>{[-1,1].map((n,i)=><mesh key={n} position={[n*.28,.2+i*.3,0]}><sphereGeometry args={[.23,24,24]}/><meshPhysicalMaterial color="#660f2b" roughness={.2} clearcoat={1}/></mesh>)}<mesh position={[0,.67,0]} rotation={[0,0,-.4]}><cylinderGeometry args={[.012,.019,.6,8]}/><meshStandardMaterial color="#8d7960"/></mesh>{[0,1,2,3,4].map(i=><mesh key={i} position={[.3+Math.sin(i*1.25)*.22,-.65+Math.cos(i*1.25)*.2,.1]} rotation={[.3,0,i*1.25]} scale={[.12,.35,.055]}><sphereGeometry args={[1,16,16]}/><meshStandardMaterial color="#a5a0c2" roughness={.55}/></mesh>)}<mesh position={[-.2,-1.15,0]} rotation={[.2,.3,.6]}><cylinderGeometry args={[.08,.12,.7,8]}/><meshStandardMaterial color="#795749" roughness={.95}/></mesh></group>
 <group ref={atmosphere} position={[1.8,0,-1.2]}><mesh position={[0,.2,-.3]} scale={[5.5,6,1]}><planeGeometry args={[1,1]}/><shaderMaterial transparent depthWrite={false} vertexShader={'varying vec2 vUv; void main(){vUv=uv; gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}'} fragmentShader={'varying vec2 vUv; void main(){float d=length((vUv-.5)*2.); float a=pow(max(0.,1.-d),2.)*.5; gl_FragColor=vec4(.42,.12,.23,a);}'}/></mesh><mesh position={[0,.22,0]} scale={[1,1.23,1]}><torusGeometry args={[1.65,.003,6,120]}/><meshBasicMaterial color="#9a7482" transparent opacity={.2}/></mesh><mesh position={[0,-1.32,.4]} scale={[3,.25,1]}><planeGeometry args={[1,1]}/><shaderMaterial transparent depthWrite={false} vertexShader={'varying vec2 vUv; void main(){vUv=uv; gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}'} fragmentShader={'varying vec2 vUv; void main(){float d=length((vUv-.5)*2.); gl_FragColor=vec4(0.,0.,0.,pow(max(0.,1.-d),2.)*.6);}'}/></mesh></group>
 <ambientLight intensity={.85}/><spotLight position={[3,5,5]} intensity={55} angle={.6} penumbra={1} color="#f7eade"/><pointLight ref={light} position={[-3,1,2]} intensity={8}/><Environment resolution={128}><Lightformer intensity={5} position={[-4,1,3]} scale={[1.5,8,1]}/><Lightformer intensity={3} position={[4,2,1]} scale={[2,7,1]}/><Lightformer intensity={2} position={[0,2,5]} scale={[3,2,1]}/><Lightformer intensity={2} position={[0,5,-2]} rotation={[Math.PI/2,0,0]} scale={[5,4,1]}/></Environment>{!reduced&&<Sparkles count={24} size={1.2} scale={[10,7,5]} speed={.12} opacity={.16} color="#e7d7d9"/>}</>;
}
export default function BottleScene({pose,reduced,onReady,onFailure}:{pose:React.RefObject<Pose>;reduced:boolean;onReady:()=>void;onFailure:()=>void}) {return <Canvas dpr={[1,1.5]} camera={{position:[0,.25,6.8],fov:35}} gl={{antialias:true,alpha:false,powerPreference:'high-performance'}} onCreated={onReady}><ContextEvents onFailure={onFailure}/><Suspense fallback={null}><Bottle pose={pose} reduced={reduced}/></Suspense></Canvas>;}

function ContextEvents({onFailure}:{onFailure:()=>void}){const gl=useThree(s=>s.gl);useEffect(()=>{const canvas=gl.domElement;canvas.addEventListener('webglcontextlost',onFailure);return()=>canvas.removeEventListener('webglcontextlost',onFailure);},[gl,onFailure]);return null;}
