'use client';
import dynamic from 'next/dynamic';
import SignatureFooter from './SignatureFooter';
import { useEffect, useRef, useState } from 'react';
import { ArrowUpRight, ArrowDown, ArrowLeft, ArrowRight, Plus, Minus, X, ShoppingBag, Menu } from 'lucide-react';
import gsap from 'gsap';
import { ScrollTrigger } from 'gsap/ScrollTrigger';
import Lenis from 'lenis';
import type { Pose } from './BottleScene';
const CollectionBottle=dynamic(()=>import('./CollectionBottle'),{ssr:false});
const Scene=dynamic(()=>import('./BottleScene'),{ssr:false});
const products=[{id:'night',name:'Night Bloom',notes:'Dark cherry · Iris · Cedarwood',family:'FLORAL / WOODY',color:'#7c2e43',description:'The quiet intensity of a night in bloom. Juicy dark cherry opens into powdery iris, settling on a warm, dry cedarwood trail.',prices:[590,890,1290]},{id:'silver',name:'Silver Skin',notes:'Bergamot · White musk · Sandalwood',family:'MUSK / FRESH',color:'#aaa79b',description:'A soft second skin. Bright bergamot gives way to airy white musk and the smooth warmth of sandalwood.',prices:[550,850,1250]},{id:'rose',name:'Velvet Rose',notes:'Pink pepper · Rose · Amber',family:'FLORAL / AMBER',color:'#af5260',description:'A rose with a little edge. Pink pepper brings a gentle spark to plush petals, wrapped in a lingering amber warmth.',prices:[620,920,1390]}];
type Product=typeof products[number];type Item={id:string;size:number;quantity:number};const sizes=[30,50,100];const money=(n:number)=>`${n.toLocaleString('en-US')} MAD`;
function MiniBottle({color}:{color:string}){return <div className="mini-bottle" style={{'--juice':color} as React.CSSProperties}><div className="mini-cap"/><div className="mini-neck"/><div className="mini-glass"><div className="mini-liquid"/><div className="mini-label"><small>EAU DE PARFUM</small><b>SHANNA</b><span>THE SIGNATURE COLLECTION</span></div></div></div>;}
export default function Storefront(){
 const collectionTrack=useRef<HTMLDivElement>(null);const [activeProduct,setActiveProduct]=useState(0);function goToProduct(index:number){const track=collectionTrack.current;if(!track)return;const card=track.children[index] as HTMLElement;track.scrollTo({left:card.offsetLeft-(track.children[0] as HTMLElement).offsetLeft,behavior:reduced?'instant':'smooth'});}
 const journey=useRef<HTMLDivElement>(null),pose=useRef<Pose>({x:1.8,y:-.12,ry:-.28,rz:-.12,camera:7.6,cap:0,berry:0,notes:0});const [reduced,setReduced]=useState(false),[supported,setSupported]=useState<boolean|null>(null),[ready,setReady]=useState(false),[menu,setMenu]=useState(false),[selected,setSelected]=useState<Product|null>(null),[size,setSize]=useState(50),[cart,setCart]=useState<Item[]>([]),[loaded,setLoaded]=useState(false),[cartOpen,setCartOpen]=useState(false),[announcement,setAnnouncement]=useState('');const productDialog=useRef<HTMLDialogElement>(null),cartDialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{const media=matchMedia('(prefers-reduced-motion: reduce)');const update=()=>setReduced(media.matches);update();media.addEventListener('change',update);try{const c=document.createElement('canvas');setSupported(!!(c.getContext('webgl2')||c.getContext('webgl')));}catch{setSupported(false);}try{const data=JSON.parse(localStorage.getItem('shanna-cart')||'[]');if(Array.isArray(data))setCart(data.filter((x:Item)=>products.some(p=>p.id===x.id)&&sizes.includes(x.size)&&Number.isInteger(x.quantity)&&x.quantity>0).map((x:Item)=>({...x,quantity:Math.min(x.quantity,99)})));}catch{}setLoaded(true);return()=>media.removeEventListener('change',update);},[]);
 useEffect(()=>{if(loaded)try{localStorage.setItem('shanna-cart',JSON.stringify(cart));}catch{}},[cart,loaded]);
 useEffect(()=>{gsap.registerPlugin(ScrollTrigger);const lenis=reduced?null:new Lenis({duration:1.05,smoothWheel:true});const tick=(time:number)=>lenis?.raf(time*1000);lenis?.on('scroll',ScrollTrigger.update);if(lenis)gsap.ticker.add(tick);const context=gsap.context(()=>{const panels=gsap.utils.toArray<HTMLElement>('.chapter');gsap.set(panels.slice(1),{autoAlpha:0,y:24});const tl=gsap.timeline({scrollTrigger:{trigger:journey.current,start:'top top',end:'bottom bottom',scrub:reduced?true:1},defaults:{ease:'power1.inOut'}});const frames=[{x:.5,y:0,ry:Math.PI*1.85,rz:.07,camera:5.8,cap:0,berry:1,notes:0},{x:1.2,y:0,ry:Math.PI*2-.32,rz:-.09,camera:6.7,cap:0,berry:.55,notes:1},{x:.8,y:-.25,ry:Math.PI*2+.38,rz:.04,camera:6,cap:.65,berry:.15,notes:0},{x:.25,y:0,ry:Math.PI*2-.12,rz:-.08,camera:7.1,cap:0,berry:0,notes:0}];frames.forEach((f,i)=>{tl.to(pose.current,reduced?{...f,ry:-.18,rz:0,cap:0,camera:6.8}:{...f,duration:1},i);tl.to(panels[i],{autoAlpha:0,y:-20,duration:.35},i+.35);tl.fromTo(panels[i+1],{autoAlpha:0,y:24},{autoAlpha:1,y:0,duration:.35},i+.55);});tl.to('.journey-progress',{scaleX:1,duration:4,ease:'none'},0);},journey);return()=>{context.revert();gsap.ticker.remove(tick);lenis?.destroy();};},[reduced]);
 useEffect(()=>{if(selected)productDialog.current?.showModal();else productDialog.current?.close();},[selected]);useEffect(()=>{if(cartOpen)cartDialog.current?.showModal();else cartDialog.current?.close();},[cartOpen]);
 useEffect(()=>{if(!selected&&!cartOpen&&!menu)return;const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=old;};},[selected,cartOpen,menu]);
 const count=cart.reduce((n,x)=>n+x.quantity,0),total=cart.reduce((n,x)=>n+products.find(p=>p.id===x.id)!.prices[sizes.indexOf(x.size)]*x.quantity,0);function add(){if(!selected)return;setCart(old=>{const found=old.find(x=>x.id===selected.id&&x.size===size);return found?old.map(x=>x===found?{...x,quantity:Math.min(x.quantity+1,99)}:x):[...old,{id:selected.id,size,quantity:1}];});setAnnouncement(`${selected.name}, ${size} ml added to your bag`);setSelected(null);setCartOpen(true);}function quantity(item:Item,delta:number){setCart(old=>old.map(x=>x.id===item.id&&x.size===item.size?{...x,quantity:Math.min(99,x.quantity+delta)}:x).filter(x=>x.quantity>0));}
 return <><a className="skip-link" href="#collection">Skip to collection</a><header className="site-header"><a className="wordmark" href="#" aria-label="SHANNA home">SHANNA<span>PARFUMS</span></a><nav className="desktop-nav" aria-label="Main navigation"><a href="#journey">The experience</a><a href="#collection">The collection</a></nav><div className="header-actions"><span className="edition">INDEPENDENT IN SPIRIT.</span><button className="bag-button" onClick={()=>setCartOpen(true)} aria-label={`Open bag, ${count} items`}>Bag <span>({count})</span><ShoppingBag size={16}/></button><button className="mobile-toggle" onClick={()=>setMenu(!menu)} aria-label="Toggle navigation" aria-expanded={menu}>{menu?<X/>:<Menu/>}</button></div></header>
 {menu&&<nav className="mobile-menu" aria-label="Mobile navigation" onKeyDown={e=>{if(e.key==='Escape')setMenu(false);}}><a href="#journey" onClick={()=>setMenu(false)}>The experience <ArrowUpRight/></a><a href="#collection" onClick={()=>setMenu(false)}>The collection <ArrowUpRight/></a></nav>}
 <main><div id="journey" ref={journey} className="journey"><div className="stage"><div className="canvas-layer" aria-hidden="true">{supported===true?<Scene pose={pose} reduced={reduced} onReady={()=>setReady(true)} onFailure={()=>setSupported(false)}/>:<div className="fallback-bottle"><MiniBottle color="#7c2e43"/></div>}</div>{supported===true&&!ready&&<div className="loading">SETTING THE SCENE <span/></div>}<div className="stage-grain"/><div className="hero-overline">COLLECTION 01 / THE ART OF PRESENCE <span>EAU DE PARFUM</span></div>
 <section className="chapter intro"><div className="chapter-eyebrow">01 / THE FIRST IMPRESSION</div><h1>A scent.<br/><em>A signature.</em></h1><div className="intro-bottom"><p>An invisible presence.<br/>An unforgettable impression.</p><a className="text-link" href="#reveal" onClick={e=>{e.preventDefault();window.scrollTo({top:window.innerHeight*1.1,behavior:reduced?'instant':'smooth'});}}>Discover Shanna <ArrowUpRight size={19}/></a></div><span className="bottle-caption">NIGHT BLOOM<br/><small>50 ML — EAU DE PARFUM</small></span></section>
 <section className="chapter reveal" id="reveal"><div className="chapter-eyebrow">02 / THE REVEAL</div><h2>Made to be<br/><em>remembered.</em></h2><p>A little mystery. An unmistakable presence.<br/>A fragrance that speaks before you do.</p></section>
 <section className="chapter notes"><div className="chapter-eyebrow">03 / THE COMPOSITION</div><h2>A story.<br/><em>In three notes.</em></h2><div className="notes-list">{['Dark Cherry','Iris','Cedarwood'].map((n,i)=><div key={n}><small>0{i+1} / {['TOP','HEART','BASE'][i]}</small><span>{n}</span><i>{['Luscious. Unexpected.','Soft. Intriguing.','Warm. Enduring.'][i]}</i></div>)}</div></section>
 <section className="chapter details"><div className="chapter-eyebrow">04 / EVERY DETAIL</div><h2>Presence,<br/><em>by design.</em></h2><p>Cool metal. Sculpted glass. A weight that feels right.<br/>An object as considered as the scent within.</p><span className="detail-callout">THE FINISHING TOUCH <span>↗</span></span></section>
 <section className="chapter signature"><div className="chapter-eyebrow">05 / MAKE IT YOURS</div><h2>Leave your<br/><em>signature.</em></h2><a className="text-link" href="#collection">Explore the collection <ArrowUpRight size={19}/></a></section>
 <div className="stage-bottom"><span><span className="live-dot"/> A STUDY IN CONTRAST</span><span className="scroll-cue">SCROLL TO UNFOLD THE STORY <ArrowDown size={13}/></span><span>DARK CHERRY / IRIS / CEDARWOOD</span></div><div className="journey-progress"/></div></div>
 <section id="collection" className="collection"><div className="collection-heading"><div><span className="eyebrow"><span className="collection-status"/> THE SIGNATURE COLLECTION / 01</span><h2>The next dimension<br/>of <em>you.</em></h2></div><div className="collection-intro"><span>SCENT, BEYOND THE ORDINARY.</span><p>Three worlds. One signature.<br/>Find the expression that feels like you.</p><span className="collection-interaction">MOVE TO EXPLORE <ArrowUpRight size={14}/></span></div></div><div className="products" ref={collectionTrack} id="collection-track" aria-label="Fragrance collection" data-lenis-prevent onScroll={e=>{const track=e.currentTarget;const first=track.children[0] as HTMLElement;const next=track.children[1] as HTMLElement;setActiveProduct(Math.max(0,Math.min(2,Math.round(track.scrollLeft/(next.offsetLeft-first.offsetLeft)))));}}>{products.map((p,i)=><button key={p.id} className={`product product-${p.id}`} onClick={()=>{setSize(50);setSelected(p);}} aria-label={`Explore ${p.name}`}><div className="product-visual"><div className="product-top"><span>0{i+1}</span><span>{p.family}</span></div><div className="scent-orbit" aria-hidden="true"/><span className="scent-ghost" aria-hidden="true">{['NOCTURNE','ELEMENTAL','RADICAL'][i]}</span>{supported===true?<CollectionBottle color={p.color} name={p.name} reduced={reduced} fallback={<MiniBottle color={p.color}/>}/>:<MiniBottle color={p.color}/>}<span className="product-explore">ENTER THE SCENT <span className="explore-plus"><Plus size={19}/></span></span></div><div className="product-title"><h3>{p.name}</h3><ArrowUpRight size={23}/></div><p>{p.notes}</p><span className="price">From {money(p.prices[0])}</span></button>)}</div><div className="collection-controls"><span>SWIPE TO DISCOVER</span><div className="collection-pagination" aria-label="Choose a fragrance">{products.map((p,i)=><button key={p.id} aria-label={`Show ${p.name}`} aria-current={activeProduct===i?'true':undefined} onClick={()=>goToProduct(i)}><span/></button>)}</div><div className="collection-arrows"><button aria-label="Previous fragrance" disabled={activeProduct===0} onClick={()=>goToProduct(activeProduct-1)}><ArrowLeft size={17}/></button><button aria-label="Next fragrance" disabled={activeProduct===2} onClick={()=>goToProduct(activeProduct+1)}><ArrowRight size={17}/></button></div></div><div className="collection-footnote"><span>EAU DE PARFUM · 30 / 50 / 100 ML</span><span>A concept collection. An invitation to explore.</span></div></section>
 </main><SignatureFooter/>
 <dialog ref={productDialog} className="product-dialog" onCancel={()=>setSelected(null)} onClick={e=>{if(e.target===e.currentTarget)setSelected(null);}} aria-labelledby="product-name" data-lenis-prevent>{selected&&<div className="product-modal-content"><button className="close-button" aria-label="Close product details" onClick={()=>setSelected(null)}><X/></button><div className={`modal-visual product-${selected.id}`}><MiniBottle color={selected.color}/></div><div className="modal-copy"><span className="eyebrow">SHANNA / EAU DE PARFUM</span><h2 id="product-name">{selected.name}</h2><p>{selected.description}</p><p className="modal-notes">{selected.notes}</p><fieldset><legend>Select your size</legend><div className="size-options">{sizes.map(s=><button key={s} aria-pressed={size===s} onClick={()=>setSize(s)}>{s} ml</button>)}</div></fieldset><div className="modal-price">{money(selected.prices[sizes.indexOf(size)])}</div><button className="solid-button" onClick={add}>Add to bag <Plus size={18}/></button><small className="preview-note">Concept fragrance · Illustrative pricing · Checkout preview</small></div></div>}</dialog>
 <dialog ref={cartDialog} className="cart-dialog" onCancel={()=>setCartOpen(false)} onClick={e=>{if(e.target===e.currentTarget)setCartOpen(false);}} aria-labelledby="bag-title" data-lenis-prevent><div className="cart-content"><div className="cart-header"><h2 id="bag-title">Your bag <span>({count})</span></h2><button aria-label="Close bag" onClick={()=>setCartOpen(false)}><X/></button></div>{cart.length===0?<div className="empty-cart"><ShoppingBag size={37} strokeWidth={1}/><h3>A little room for a signature.</h3><p>Your bag is waiting to be discovered.</p><button className="solid-button" onClick={()=>{setCartOpen(false);document.querySelector('#collection')?.scrollIntoView({behavior:reduced?'instant':'smooth'});}}>Explore the collection <ArrowUpRight size={18}/></button></div>:<><div className="cart-items">{cart.map(item=>{const p=products.find(p=>p.id===item.id)!;return <div className="cart-item" key={item.id+item.size}><div className="cart-thumb"><MiniBottle color={p.color}/></div><div><h3>{p.name}</h3><p>EAU DE PARFUM · {item.size} ML</p><div className="quantity"><button aria-label={`Decrease ${p.name} quantity`} onClick={()=>quantity(item,-1)}><Minus size={13}/></button><span>{item.quantity}</span><button aria-label={`Increase ${p.name} quantity`} onClick={()=>quantity(item,1)}><Plus size={13}/></button></div><button className="remove" onClick={()=>setCart(old=>old.filter(x=>!(x.id===item.id&&x.size===item.size)))}>Remove</button></div><strong>{money(p.prices[sizes.indexOf(item.size)]*item.quantity)}</strong></div>;})}</div><div className="cart-summary"><div><span>Subtotal</span><strong>{money(total)}</strong></div><p>Shipping and taxes are not calculated in this preview.</p><button className="solid-button" disabled>Checkout — preview only</button><p className="checkout-notice">This is a concept store. Checkout will become available when a payment provider is connected. No payment can be taken.</p></div></>}</div></dialog><div className="sr-only" role="status" aria-live="polite">{announcement}</div></>;
}
